### ISSUE TITLE
Can't cross compile for armv7-linux-androideabi

### ISSUE THREAD

**Issue by thegedge** [ArturKovacs/trash#10]
Copied from https://github.com/nushell/nushell/issues/1556

---

When trying to build (cross-compile) Nushell for armv7-linux-androideabi platform, it gives some bugs: `use of undeclared type or module platform`

```rust
Compiling trash v1.0.0
error[E0433]: failed to resolve: use of undeclared type or module `platform`
  --> D:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.0\src\lib.rs:49:5
   |
49 |     platform::remove(path)
   |     ^^^^^^^^ use of undeclared type or module `platform`

error[E0433]: failed to resolve: use of undeclared type or module `platform`
  --> D:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.0\src\lib.rs:71:5
   |
71 |     platform::remove_all(paths)
   |     ^^^^^^^^ use of undeclared type or module `platform`

error[E0433]: failed to resolve: use of undeclared type or module `platform`
  --> D:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.0\src\lib.rs:76:5
   |
76 |     platform::is_implemented()
   |     ^^^^^^^^ use of undeclared type or module `platform`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `trash`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by ArturKovacs** [comment]
I looked into this a bit and found that the `target_os` option for the `armv7-linux-androideabi` triplet is "android" instead of "linux". If I get this right then this triplet targets a linux operating system which runs on an armv7 cpu and potentially has a full blown desktop environment. Is this correct @thegedge? In that case `trash` should have no issue functioning the exact same way as it does on an x86 linux.

Trash currently uses `#[cfg(target_os = "linux")]` to detect that the target is Linux and I don't know of any other way to do that so I'm open to suggestions. Furthermore could this be a cargo/rustc issue?

**Comment by thegedge** [comment]
I'll loop in @Star191, who reported this issue on nushell. I'm not super familiar with this triplet, so they probably have a better idea of what may work or not work on it 🙂

**Comment by thegedge** [comment]
@star191 is there a trash feature on Android? Perhaps this is a "wont fix" kind of issue, because there shouldn't be a trash feature on that platform.

**Comment by star191** [comment]
@thegedge I don't find any information about standard recycle bin (trash) on Android 9 (but you can do this with third-party apps), so I think is not there a this feature on that platform.

**Comment by thegedge** [comment]
@ArturKovacs then perhaps this is just an unsupported platform, and nushell should disable the feature on that platform. What do you think?

**Comment by ArturKovacs** [comment]
Yes, that's what I thought as well.

For the record I'd like to add that I'm absolutely willing to implement trash for platforms that define a similar concept but then it doesn't seem that that's the case for Android.
